variables:
  node_version: "10.x"

trigger:
  - azure-test

jobs:
  - job: Windows
    pool:
      vmImage: "vs2017-win2016"
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: $(node_version)
      - script: yarn install
      - script: yarn build:desktop-azure
      - task: DownloadPipelineArtifact@1
        inputs:
          buildType: 'current'
          targetPath: '/dist'

  - job: macOS
    pool:
      vmImage: "macOS-10.14"
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: $(node_version)
      - script: yarn install
      - script: yarn build:desktop-azure
      - task: DownloadPipelineArtifact@1
        inputs:
          buildType: 'current'
          targetPath: '/dist'