// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewTask struct {
	Command string `json:"command"`
	Path    string `json:"path"`
}

type Task struct {
	ID      string `json:"id"`
	Command string `json:"command"`
	Path    string `json:"path"`
	Pid     int    `json:"pid"`
	Running bool   `json:"running"`
}
